name: Build Elder Launcher APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install NDK and Platform 34
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653"
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed

      - name: Build APK
        working-directory: ./android
        run: |
          chmod +x gradlew
          ./gradlew :MainApp:assembleDebug --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Elder-Launcher-APK
          path: |
            android/**/build/outputs/apk/debug/*.apk
            android/**/build/outputs/apk/release/*.apk